### ISSUE TITLE
TypeError: softmax() got an unexpected keyword argument 'axis'

### ISSUE THREAD

**Issue by dfki-bruce** [sadeepj/crfasrnn_keras#29] opened 2018-04-07 19:33 UTC
Hello!
I am trying your **tensorflow version** code(crfasrnn_keras), but I met an error,the following contents are the errors:

**(tensorflow) bruce@ubuntu:**~/master_thesis/crfasrnn_keras$ python3 run_demo.py
/home/bruce/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "run_demo.py", line 48, in <module>
    main()
  File "run_demo.py", line 38, in main
    model = get_crfrnn_model_def()
  File "./src/crfrnn_model.py", line 111, in get_crfrnn_model_def
    name='crfrnn')([upscore, img_input])
  File "/home/bruce/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "./src/crfrnn_layer.py", line 91, in call
    softmax_out = tf.nn.softmax(q_values, axis=0)
**TypeError: softmax() got an unexpected keyword argument 'axis'**

and my computer configuration are:
**ubuntu 16.04 on VMware player 14, host system is win 10,CPU core I5**

Thank you very much for your answer!

Bruce

**Comment by sadeepj** [comment] 2018-04-08 11:36
@dfki-bruce What's your Tensorflow version? I think the cause of this error is an older version of Tensorflow (see https://www.tensorflow.org/api_docs/python/tf/nn/softmax - 'axis' is the right keyword argument for newer versions of Tensorflow).

Updating your Tensorflow version (see https://www.tensorflow.org/install/) should solve this problem. Please let me know if it doesn't.

**Comment by dfki-bruce** [comment] 2018-04-08 18:58
@sadeepj 
Thank you so much for your fast reply!
My TF version is 1.2.1.
I will try to upgrade my TF and let you know the results.\
Best,

**Comment by sadeepj** [comment] 2018-04-08 19:02
@dfki-bruce Alternatively, as a workaround for older Tensorflow versions, you can change the parameter name 'axis' to 'dim' in Line 91 of crfrnn_layer.py (https://github.com/sadeepj/crfasrnn_keras/blob/4819142eaf3788f9ce6945edfcc5d73aa0aa7f70/src/crfrnn_layer.py#L91).

**Comment by dfki-bruce** [comment] 2018-04-08 20:45
@sadeepj ,
Thank you for your  advice!
I just upgraded my TF to 1.7.0,
and the errors are:
**(tensorflow) bruce@ubuntu:**~/master_thesis/crfasrnn_keras$ python run_demo.py 
/home/bruce/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "run_demo.py", line 27, in <module>
    from crfrnn_model import get_crfrnn_model_def
  File "./src/crfrnn_model.py", line 28, in <module>
    from crfrnn_layer import CrfRnnLayer
  File "./src/crfrnn_layer.py", line 28, in <module>
    import high_dim_filter_loader
  File "./src/high_dim_filter_loader.py", line 28, in <module>
    custom_module = tf.load_op_library(os.path.join(os.path.dirname(__file__), 'cpp', 'high_dim_filter.so'))
  File "/home/bruce/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/bruce/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
**tensorflow.python.framework.errors_impl.NotFoundError: ./src/cpp/high_dim_filter.so: undefined symbol: _ZTIN10tensorflow8OpKernelE**

So maybe I will downgrade my TF and try your new advice, change the axis to dim.
Thank you!

**Comment by sadeepj** [comment] 2018-04-08 21:02
@dfki-bruce You'd have to remake the high_dim_filter.so file after upgrading Tensorflow:
$ cd crfasrnn_keras/src/cpp
$ rm *.so
$ make

**Comment by dfki-bruce** [comment] 2018-04-09 00:11
@sadeepj ,
Thank you again for your solution!
I tried and it partially works,following the error:
**Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2**,
however ,strictly speakings, it is not an error according to [**here**](https://stackoverflow.com/questions/47068709/your-cpu-supports-instructions-that-this-tensorflow-binary-was-not-compiled-to-u)
so anyway I will try again,
thanks!

**Comment by dfki-bruce** [comment] 2018-04-09 11:01
@sadeepj 
Good morning!
Finally, the result "lables.png" was generated, following the error
**"I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA"**
and the output pic is not as exactly  same as "sample.png",see attach 1.
So I think it should be the right result as it would be,right?
THanks!

Attach 1
![labels](https://user-images.githubusercontent.com/33227708/38494377-0519b524-3bf6-11e8-9988-47ee17508f1b.png)

**Comment by sadeepj** [comment] 2018-04-09 13:29
@dfki-bruce That's the correct result. What you're seeing is a Tensorflow warning message (not an error) that you can safely ignore. It has nothing to do with the code in the repo, hence closing this issue.

**Closed by sadeepj** 2018-04-09 13:29 UTC
